# Generated by Django 4.2.26 on 2025-12-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpass', '0002_alter_event_options_alter_survey_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
