# Generated by Django 5.2.9 on 2025-12-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpass', '0003_event_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
