# Generated by Django 5.2.9 on 2025-12-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpass', '0004_attendance_time_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='certificate_template',
            field=models.CharField(choices=[('default', 'Default Template'), ('modern', 'Modern Template'), ('classic', 'Classic Template')], default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='max_capacity',
            field=models.IntegerField(default=0, help_text='0 means unlimited'),
        ),
    ]
