# Generated by Django 5.2.9 on 2025-12-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpass', '0006_event_category_event_recurrence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='certificate_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='certificate_modifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='attendance',
            name='certificate_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='classification',
            field=models.CharField(choices=[('PUBLIC', 'Public - Everyone can see'), ('STUDENTS', 'Students Only'), ('FACULTY', 'Faculty Only'), ('ADMIN', 'Admin Only'), ('RESTRICTED', 'Restricted - Invite Only')], default='PUBLIC', max_length=20),
        ),
    ]
