# Generated by Django 5.2.9 on 2025-12-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpass', '0007_attendance_certificate_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='academic_year',
            field=models.CharField(blank=True, help_text='e.g., 2024-2025', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='semester',
            field=models.CharField(choices=[('1ST', '1st Semester'), ('2ND', '2nd Semester'), ('SUMMER', 'Summer'), ('NONE', 'Not Applicable')], default='NONE', max_length=10),
        ),
    ]
