# Generated by Django 5.2.9 on 2025-12-19 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpass', '0008_event_academic_year_event_semester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['event', 'attendee'], name='vpass_atten_event_i_224a13_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['timestamp'], name='vpass_atten_timesta_2b4711_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['present'], name='vpass_atten_present_b03661_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start', 'end'], name='vpass_event_start_a996a6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by'], name='vpass_event_created_604bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category'], name='vpass_event_categor_24d6a3_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['classification'], name='vpass_event_classif_3bf37b_idx'),
        ),
    ]
